swagger: "2.0"
info:
  description: Run usql in Direktiv
  title: usql
  version: "1.0"
  x-direktiv-meta:
    container: gcr.io/direktiv/functions/usql
    maintainer: |-
      [direktiv.io](https://www.direktiv.io) 
    issues: https://github.com/direktiv-apps/usql/issues
    url: https://github.com/direktiv-apps/usql  
    categories:
    - database
    license: |-
      [Apache-2.0](https://www.apache.org/licenses/LICENSE-2.0)
    long-description: >-
      [Usql](https://github.com/xo/usql) is a universal command-line interface for PostgreSQL, MySQL, Oracle Database, SQLite3, Microsoft SQL Server, and many other databases including NoSQL and non-relational databases. 
      This service provides easy access to database from Direktiv and supports variables and interpolation as well. 

      The connection string has to be URL-encoded!
consumes:
- application/json
produces:
- application/json
schemes:
- http
paths:
  /: 
    delete:
      parameters:
        - name: Direktiv-ActionID
          in: header
          type: string
          description: |
            On cancel Direktiv sends a DELETE request to
            the action with id in the header
      x-direktiv:
        cancel: echo 'cancel {{ .DirektivActionID }}'
      responses:
        200:
    post:
      parameters:
        - name: Direktiv-ActionID
          in: header
          type: string
          default: development
          description: |
            direktiv action id is an UUID. 
            For development it can be set to 'development'
        - name: Direktiv-TempDir
          in: header
          type: string
          default: /tmp
          description: |
            direktiv temp dir is the working directory for that request
            For development it can be set to e.g. '/tmp'
        - name: body
          in: body
          schema:
            type: object
            required: ["connection"]
            properties:
              connection:
                type: string
                example: pg://myuser:mypwd@MYDATABAESERVER:5432
                description: Connection string for sql commands. This will be used for all commands and has to be URL-encoded. 
              queries:
                description: >
                  List of sql commands. Commands can use interpolation:<br/>
                  query: select * from table where id = :'ID'<br/>
                  args: ID=123
                example:
                  query: select * from mytable where key = :'KEY'
                  args: 
                    - KEY=1
                type: array
                items:
                  type: object
                  properties:
                    query:
                      type: string
                      example: select * from table where value = :'ARG'
                    args:
                      type: array
                      example: ARG=myarg
                      items: 
                        type: string
      # direktiv code generation is configured here
      x-direktiv-function: |-
        functions:
        - id: usql
          image: gcr.io/direktiv/functions/usql:1.0
          type: knative-workflow
      x-direktiv-examples:
        - title: Simple Query
          content: |-
            - id: usql
              type: action
              action:
                function: usql
                input: 
                  connection: pg://direktiv:Nyjn_%28_6%7B2P%7DD8z18xH%3F%3AM1M@10.100.6.7:5432/direktiv
                  queries:
                  - query: select * from namespaces
              catch:
              - error: "*"
        - title: Query with Arguments
          content: |-
            - id: usql
              type: action
              action:
                function: usql
                input: 
                  connection: pg://direktiv:Nyjn_%28_6%7B2P%7DD8z18xH%3F%3AM1M@10.100.6.7:5432/direktiv
                  queries:
                  - query: select * from namespaces where oid = :'ARG'
                    args:
                    - ARG=9f81ab5b-aa13-4393-bbd6-adce3d2da958
              catch:
              - error: "*"
      x-direktiv-secrets:
        - name: sqlconnection
          description: The database connection string
      x-direktiv:  
        cmds:
        - action: foreach
          loop: .Queries
          exec: |-
            usql {{ .Body.Connection }} -c "{{ .Item.Query }}" -J --set SHOW_HOST_INFORMATION=false 
            {{- range .Item.Args }} --set={{.}} {{- end}}
          print: false
        output: |
          {
            "usql": {{ index . 0 | toJson }}
          }
      x-direktiv-errors:
        io.direktiv.command.error: Command execution failed
        io.direktiv.output.error: Template error for output generation of the service
        io.direktiv.ri.error: Can not create information object from request
      responses:
        200:
          description: List of executed sql commands.
          examples:
            usql:
            - result:
              - name: world
                oid: 9f81ab5b-aa13-4393-bbd6-adce3d2da958
                updated_at: '2022-09-12T09:34:27.449133Z'
              - created_at: '2022-09-22T14:48:39.699932Z'
                name: hello
                oid: 4b48243f-bf78-455d-858a-bbf0d6c9d654
                updated_at: '2022-09-22T14:48:39.699933Z'
              success: true
          schema:
            type: object
            additionalProperties: {}
        default:
          description: generic error response
          headers:
            Direktiv-ErrorCode:
              type: string
            Direktiv-ErrorMessage:
              type: string
          schema:
            $ref: "#/definitions/error"
definitions:
  direktivFile:
    type: object
    x-go-type:
      type: DirektivFile
      import:
        package: github.com/direktiv/apps/go/pkg/apps 
  error:
    type: object
    required:
      - errorCode
      - errorMessage
    properties:
      errorCode:
        type: string
      errorMessage:
        type: string
